# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_x', models.IntegerField()),
                ('room_y', models.IntegerField()),
                ('direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West'), ('U', 'Up'), ('D', 'Down')], max_length=1)),
                ('destination', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maze.Passage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='passage',
            unique_together=set([('room_x', 'room_y', 'direction')]),
        ),
    ]
